### ISSUE TITLE
try/catch in useEffect

### ISSUE THREAD

**Issue by Anber** [kleshninpo/messages_list#1]
https://github.com/kleshninpo/messages_list/blob/77e46cd852f94c8062f9163d37887260d6faaba5/src/Components/AuthorPage.tsx#L19

Вот этот catch никогда не отработает. Почему и как это исправить?

**Comment by kleshninpo** [comment]
Тооочно.

Почему – потому что try/catch не отлавливает исключения, брошенные внутри промиса.
Как это исправить – для этого нужно убрать try/catch и использовать Promise.catch() после .then, чейнингом.
Поправил 👍
