### ISSUE TITLE
SearchPanel.tsx

### ISSUE THREAD

**Issue by Anber** [kleshninpo/messages_list#3]
https://github.com/kleshninpo/messages_list/blob/77e46cd852f94c8062f9163d37887260d6faaba5/src/Components/SearchPanel.tsx#L17C1-L17C1 обе эти константы не зависят от пропсов или других переменных внутри компонента, а значит их можно вынести из компонента, чтобы повысить читабельность.

enum'ы — это вроде как наглядно, но в TS они получились очень так себе и прямо в документации по ним рекомендуется их не использовать https://www.typescriptlang.org/docs/handbook/enums.html#objects-vs-enums. По сути, тут бы просто хватило юниона или чего-то такого:
```
const FilterTypes = ["author", "message"] as const;
type EFilterType = typeof FilterTypes[number];
```

**Comment by kleshninpo** [comment]
Точно, константы вынес 👍 

С энумами – по старой памяти юзаю их, на всех предыдущих проектах были, удобно было поиском по проекту их искать, но я тоже слышал не раз нелестные отзывы об их реализации, так что мне не принципиально – предложенный вариант удобный, его использовал 🙂
