### ISSUE TITLE
Modal.tsx

### ISSUE THREAD

**Issue by Anber** [kleshninpo/messages_list#4]
https://github.com/kleshninpo/messages_list/blob/77e46cd852f94c8062f9163d37887260d6faaba5/src/Components/Modal.tsx#L32 железный лимит символов формально соответсвует условию задачи, но с точки зрения пользователя, мягкая валидация была бы куда удобнее, так как не обрубает скопированный в поле текст и позволяет подогнать его по размеру.

https://github.com/kleshninpo/messages_list/blob/messages_list/src/Components/Modal.tsx#L12 лишний стейт, так как является примитивной производной от `newText`.

**Comment by kleshninpo** [comment]
Согласен, посмотрел на условие, но не подумал о UX. Добавил валидацию.

Стейт лишний тоже убрал 👍
