### ISSUE TITLE
MessagesList.tsx

### ISSUE THREAD

**Issue by Anber** [kleshninpo/messages_list#5]
https://github.com/kleshninpo/messages_list/blob/77e46cd852f94c8062f9163d37887260d6faaba5/src/Components/MessagesList.tsx#L46 к каким проблемам может привести использование индекса в качестве key?

**Comment by kleshninpo** [comment]
Массив может мутировать – ключи могут продублироваться, что породит непредвиденные последствия. Ну и внутри Реакт рассчитывает на уникальность ключа, так что может пострадать внутренняя оптимизация.
На скорую руку подставил, не думая, а так на прошлых проектах часто использовали для разных целей [uuid](https://www.npmjs.com/package/uuid)

**Comment by Anber** [comment]
Компонент в списке может быть stateful. Стейт к компоненту привязывается по его позиции в дереве и атрибуту key. И может так получиться, что у тебя компонент с одним и тем же стейтом (условно первый в списке) будет рендериться с разными пропсами. В большинстве случаев это будет незаметно, но иногда может приводить к странным последствиям. Например, если ты добавишь к сообщениям возможность их сворачивать и разворачивать (через тот же useFlag), затем развернёшь второе сообщение в списке и отфильтруешь список так, чтобы второе стало первым, то развёрнутым у тебя останется всё равно второе сообщение, так как стейт остался прибит к `key={1}`.

**Comment by kleshninpo** [comment]
Спасибо за развёрнутое пояснение)
Ну сейчас-то я уже заюзал id
<img width="657" alt="image" src="https://github.com/kleshninpo/messages_list/assets/22298969/e86edee1-0efc-4466-aedc-128cce5f12d4">
