### ISSUE TITLE
useModal.ts

### ISSUE THREAD

**Issue by Anber** [kleshninpo/messages_list#6]
https://github.com/kleshninpo/messages_list/blob/77e46cd852f94c8062f9163d37887260d6faaba5/src/hooks/useModal.ts по сути, это хук общего назначения для управления произвольным флагом. Название useModel же ограничивает его переиспользование. Ещё было бы неплохо мемоизировать колбеки, так как они могут использоваться в сложных компонентах и ломать производительность.

**Comment by kleshninpo** [comment]
Про название и переиспользование согласен, поменял на useFlag. Про мемоизацию – речь же о коллбеке `cb`, передаваемом в модалку? Завернул его в useCallback

**Comment by Anber** [comment]
Не, речь про setTrue и setFalse, которые на каждый рендер будут новыми и будут ломать мемоизацию компонентов, в которые их передают.

**Comment by kleshninpo** [comment]
Аааа, блин, ну точно 🤦 
Обернул
