### ISSUE TITLE
api.ts

### ISSUE THREAD

**Issue by Anber** [kleshninpo/messages_list#8]
addMessage тут не работает вообще. Ну и непонятно, почему тут только добавление сообщений, но не их загрузка.

**Comment by kleshninpo** [comment]
Как не работает? Как раз эта функция вызывается при клике на кнопку в модалке.
Про остальные запросы – хотел их сюда положить, но в итоге оставил fetch прямо в компонентах, т.к. они были GET и небольшие, но согласен, что лучше по уму сделать – перенёс запросы в api

**Comment by Anber** [comment]
C return стало лучше :) До этого функция возвращала управление сразу, не дожидаясь ответа от api.
